# Run Spring Boot on port 8080
server.port=8080

# Disable DB configuration failure for now:
spring.datasource.url=jdbc:postgresql://localhost:5432/dummy
spring.datasource.username=dummy
spring.datasource.password=dummy
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.continue-on-error=true
spring.jpa.hibernate.ddl-auto=none
